### ISSUE TITLE
No Such File - Curl.h

### ISSUE THREAD

**Issue by kobs0N** [P0cL4bs/kadimus#6] opened 2017-04-25 12:48 UTC
root@kali:~/Desktop# git clone https://github.com/P0cL4bs/Kadimus.git
Cloning into 'Kadimus'...

remote: Counting objects: 202, done.
remote: Total 202 (delta 0), reused 0 (delta 0), pack-reused 202
Receiving objects: 100% (202/202), 53.34 KiB | 75.00 KiB/s, done.
Resolving deltas: 100% (113/113), `done.`
_root@kali:~/Desktop# 
root@kali:~/Desktop# cd Kadimus/
root@kali:~/Desktop/Kadimus# ls
bin  configure  license.txt  Makefile  README.md  resource  src
root@kali:~/Desktop/Kadimus# ./configure 
Checking libraries...
libcurl	Ok_
libssl	Ok
libpcre	Ok
libssh	Ok
root@kali:~/Desktop/Kadimus# make
gcc -Wall -Wextra -O3 -c -o bin/kadimus_common.o src/kadimus_common.c
gcc -Wall -Wextra -O3 -c -o bin/kadimus_mem.o src/kadimus_mem.c
**gcc -Wall -Wextra -O3 -c -o bin/kadimus_request.o src/kadimus_request.c
In file included from src/kadimus_request.c:1:0:
src/kadimus_request.h:4:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>**
                       ^
compilation terminated.
Makefile:21: recipe for target 'bin/kadimus_request.o' failed
make: *** [bin/kadimus_request.o] Error 1

Error when compiling...

**Comment by rewardone** [comment] 2018-03-03 15:29
On a default installation, I had to also grab the following libraries

apt-get install libcurl4-openssl-dev libpcre++-dev

Then Kadimus was able to compile.

**Comment by slayerlab** [comment] 2018-04-16 03:39
Duplicate of #7

**Closed as completed** 2020-04-19 05:07 UTC

**Comment by pS3ud0RAnD0m** [comment] 2020-07-11 20:54
i had to 'apt-get install libssh-dev libcurl4-openssl-dev libpcre++-dev'
